"""add_audio_integration_models

Revision ID: 006e24381f33
Revises: 9f41eb57ba43
Create Date: 2026-02-13 22:27:41.041111

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '006e24381f33'
down_revision: Union[str, Sequence[str], None] = '9f41eb57ba43'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audio_tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('tag_type', sa.String(), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'name', 'tag_type', name='uq_audio_tag_org_name')
    )
    op.create_index(op.f('ix_audio_tags_id'), 'audio_tags', ['id'], unique=False)
    op.create_index(op.f('ix_audio_tags_name'), 'audio_tags', ['name'], unique=False)
    op.create_index(op.f('ix_audio_tags_org_id'), 'audio_tags', ['org_id'], unique=False)
    op.create_table('integration_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('access_token_encrypted', sa.Text(), nullable=True),
    sa.Column('refresh_token_encrypted', sa.Text(), nullable=True),
    sa.Column('token_expires_at', sa.DateTime(), nullable=True),
    sa.Column('connected_by_user_id', sa.Integer(), nullable=False),
    sa.Column('account_email', sa.String(), nullable=True),
    sa.Column('account_display_name', sa.String(), nullable=True),
    sa.Column('default_folder_path', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['connected_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'provider', name='uq_integration_org_provider')
    )
    op.create_index(op.f('ix_integration_accounts_id'), 'integration_accounts', ['id'], unique=False)
    op.create_index('ix_integration_accounts_org_id', 'integration_accounts', ['org_id'], unique=False)
    op.create_table('audio_assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('song_id', sa.Integer(), nullable=True),
    sa.Column('release_id', sa.Integer(), nullable=True),
    sa.Column('creator_id', sa.Integer(), nullable=True),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('provider_file_id', sa.String(), nullable=True),
    sa.Column('path_display', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('file_type', sa.String(), nullable=False),
    sa.Column('mime_type', sa.String(), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('checksum', sa.String(), nullable=True),
    sa.Column('last_verified_at', sa.DateTime(), nullable=True),
    sa.Column('is_available', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['creators.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['release_id'], ['releases.id'], ),
    sa.ForeignKeyConstraint(['song_id'], ['songs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audio_assets_creator_id'), 'audio_assets', ['creator_id'], unique=False)
    op.create_index(op.f('ix_audio_assets_id'), 'audio_assets', ['id'], unique=False)
    op.create_index('ix_audio_assets_org_id', 'audio_assets', ['org_id'], unique=False)
    op.create_index('ix_audio_assets_release_id', 'audio_assets', ['release_id'], unique=False)
    op.create_index('ix_audio_assets_song_id', 'audio_assets', ['song_id'], unique=False)
    op.create_table('audio_analyses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('audio_asset_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('analyzed_at', sa.DateTime(), nullable=True),
    sa.Column('bpm', sa.Float(), nullable=True),
    sa.Column('bpm_confidence', sa.Float(), nullable=True),
    sa.Column('musical_key', sa.String(), nullable=True),
    sa.Column('key_confidence', sa.Float(), nullable=True),
    sa.Column('time_signature', sa.String(), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('lufs', sa.Float(), nullable=True),
    sa.Column('peak_db', sa.Float(), nullable=True),
    sa.Column('dynamic_range', sa.Float(), nullable=True),
    sa.Column('vocal_present', sa.Boolean(), nullable=True),
    sa.Column('vocal_confidence', sa.Float(), nullable=True),
    sa.Column('energy_level', sa.String(), nullable=True),
    sa.Column('features_json', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['audio_asset_id'], ['audio_assets.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audio_analyses_asset_id', 'audio_analyses', ['audio_asset_id'], unique=False)
    op.create_index(op.f('ix_audio_analyses_audio_asset_id'), 'audio_analyses', ['audio_asset_id'], unique=True)
    op.create_index(op.f('ix_audio_analyses_id'), 'audio_analyses', ['id'], unique=False)
    op.create_index('ix_audio_analyses_org_id', 'audio_analyses', ['org_id'], unique=False)
    op.create_table('audio_asset_tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('audio_asset_id', sa.Integer(), nullable=False),
    sa.Column('audio_tag_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['audio_asset_id'], ['audio_assets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['audio_tag_id'], ['audio_tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('audio_asset_id', 'audio_tag_id', name='uq_asset_tag')
    )
    op.create_index(op.f('ix_audio_asset_tags_audio_asset_id'), 'audio_asset_tags', ['audio_asset_id'], unique=False)
    op.create_index(op.f('ix_audio_asset_tags_audio_tag_id'), 'audio_asset_tags', ['audio_tag_id'], unique=False)
    op.create_index(op.f('ix_audio_asset_tags_id'), 'audio_asset_tags', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_audio_asset_tags_id'), table_name='audio_asset_tags')
    op.drop_index(op.f('ix_audio_asset_tags_audio_tag_id'), table_name='audio_asset_tags')
    op.drop_index(op.f('ix_audio_asset_tags_audio_asset_id'), table_name='audio_asset_tags')
    op.drop_table('audio_asset_tags')
    op.drop_index('ix_audio_analyses_org_id', table_name='audio_analyses')
    op.drop_index(op.f('ix_audio_analyses_id'), table_name='audio_analyses')
    op.drop_index(op.f('ix_audio_analyses_audio_asset_id'), table_name='audio_analyses')
    op.drop_index('ix_audio_analyses_asset_id', table_name='audio_analyses')
    op.drop_table('audio_analyses')
    op.drop_index('ix_audio_assets_song_id', table_name='audio_assets')
    op.drop_index('ix_audio_assets_release_id', table_name='audio_assets')
    op.drop_index('ix_audio_assets_org_id', table_name='audio_assets')
    op.drop_index(op.f('ix_audio_assets_id'), table_name='audio_assets')
    op.drop_index(op.f('ix_audio_assets_creator_id'), table_name='audio_assets')
    op.drop_table('audio_assets')
    op.drop_index('ix_integration_accounts_org_id', table_name='integration_accounts')
    op.drop_index(op.f('ix_integration_accounts_id'), table_name='integration_accounts')
    op.drop_table('integration_accounts')
    op.drop_index(op.f('ix_audio_tags_org_id'), table_name='audio_tags')
    op.drop_index(op.f('ix_audio_tags_name'), table_name='audio_tags')
    op.drop_index(op.f('ix_audio_tags_id'), table_name='audio_tags')
    op.drop_table('audio_tags')
    # ### end Alembic commands ###
