"""initial schema

Revision ID: 9f41eb57ba43
Revises: 
Create Date: 2026-02-08 03:56:04.079588

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f41eb57ba43'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'action_items', 'placements', ['placement_id'], ['id'])
    op.add_column('song_contracts', sa.Column('contract_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'song_contracts', 'contracts', ['contract_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'song_contracts', type_='foreignkey')
    op.drop_column('song_contracts', 'contract_id')
    op.drop_constraint(None, 'action_items', type_='foreignkey')
    # ### end Alembic commands ###
