from sqlalchemy import Column, Integer, String, DateTime, ForeignKey, Boolean, Enum, Index
from sqlalchemy.orm import relationship
from datetime import datetime
import enum
from .database import Base

class OrganizationType(str, enum.Enum):
    LABEL = "LABEL"
    PUBLISHER = "PUBLISHER"
    PRODUCTION_COMPANY = "PRODUCTION_COMPANY"
    MANAGER = "MANAGER"
    INDIVIDUAL = "INDIVIDUAL"


class OrganizationMemberRole(str, enum.Enum):
    OWNER = "OWNER"
    ADMIN = "ADMIN"
    MEMBER = "MEMBER"
    CLIENT = "CLIENT"


class AccountType(str, enum.Enum):
    INDIVIDUAL = "INDIVIDUAL"
    ENTERPRISE = "ENTERPRISE"


class Organization(Base):
    __tablename__ = "organizations"
    
    id = Column(Integer, primary_key=True, index=True)
    name = Column(String, index=True)
    type = Column(String)
    account_type = Column(String, default="ENTERPRISE")
    
    display_name = Column(String, nullable=True)
    logo_url = Column(String, nullable=True)
    logo_orientation = Column(String, default="square")
    primary_color = Column(String, nullable=True)
    
    access_code = Column(String, unique=True, nullable=True, index=True)

    # Task #196 — when False (default), the in-app AI assistant is read-only
    # for this org. Flipping to True exposes the proposal/confirm write tools
    # (mark_song_registered, add_fee_to_song, update_*_status, etc.).
    assistant_write_enabled = Column(
        Boolean, default=False, nullable=False, server_default="false"
    )

    # Task #204 — when True (default), Cadence sends a welcome email to
    # newly provisioned users belonging to this org. Admins can flip OFF
    # from Settings if they prefer to onboard users manually.
    welcome_email_enabled = Column(
        Boolean, default=True, nullable=False, server_default="true"
    )

    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)
    
    members = relationship("OrganizationMember", back_populates="organization")
    creators = relationship("Creator", back_populates="organization")
    songs = relationship("Song", back_populates="organization")


class OrganizationMember(Base):
    __tablename__ = "organization_members"
    
    id = Column(Integer, primary_key=True, index=True)
    organization_id = Column(Integer, ForeignKey("organizations.id"), nullable=False, index=True)
    user_id = Column(Integer, ForeignKey("users.id"), nullable=False, index=True)
    role = Column(String, nullable=False)
    can_manage_roster = Column(Boolean, default=False)
    linked_creator_id = Column(Integer, ForeignKey("creators.id"), nullable=True)
    client_access_scope = Column(String, nullable=True, default="OWN")
    created_at = Column(DateTime, default=datetime.utcnow)
    
    organization = relationship("Organization", back_populates="members")
    user = relationship("User", back_populates="organization_memberships")
    linked_creator = relationship("Creator", foreign_keys=[linked_creator_id])

    # Legacy abbreviated index names that pre-date the SQLAlchemy
    # naming convention. Declared here so `alembic check` doesn't try
    # to drop them — they coexist with the convention-named indexes
    # generated by `index=True` on the columns above.
    __table_args__ = (
        Index("ix_org_members_org_id", "organization_id"),
        Index("ix_org_members_user_id", "user_id"),
    )
